# vk/state.py
_LAST_MESSAGE_TIME = {}
_PROCESSED_MESSAGES = set()
_PROCESSED_EVENTS = set()

_AWAITING_PROBLEM_DESC = {}
_AWAITING_NAME = {}
_AWAITING_PHONE = {}
_AWAITING_CAR_SELECTION = {}

_CAR_DATA = {}
_AWAITING_CAR_STEP = {}